2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 88
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 89
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 90
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 91
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 92
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 93
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 94
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 95
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 96
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 97
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 98
2025-04-21 17:23:42 - rotating_logger - DEBUG - This is debug message number 99
2025-04-21 17:26:35 - exception_logger - ERROR - An exception occurred
Traceback (most recent call last):
  File "C:\Users\salma\AppData\Local\Temp\ipykernel_30708\3259282278.py", line 12, in log_exception
    1 / 0
ZeroDivisionError: division by zero
2025-04-21 17:28:59 - context_logger - DEBUG - This is a debug message
2025-04-21 17:28:59 - context_logger - INFO - This is an info message
2025-04-21 17:28:59 - context_logger - WARNING - This is a warning message
2025-04-21 17:28:59 - context_logger - ERROR - This is an error message
2025-04-21 17:28:59 - context_logger - CRITICAL - This is a critical message
2025-04-21 17:30:45 - additional_context_logger - DEBUG - This is a debug message
2025-04-21 17:30:45 - additional_context_logger - INFO - This is an info message
2025-04-21 17:30:45 - additional_context_logger - WARNING - This is a warning message
2025-04-21 17:30:45 - additional_context_logger - ERROR - This is an error message
